### ISSUE TITLE
特定账号开放多点登录

### ISSUE THREAD

**Issue by reactleaner** [hackycy/sf-nest-admin#16]
作者你好！我想问下怎么对特定的账号开放多点登录，刚接触nodejs后端，不是很懂要改哪里，希望作者指点一二，感谢🙏

**Comment by hackycy** [comment]
https://github.com/hackycy/sf-nest-admin/blob/dev/src/modules/admin/login/login.service.ts
https://github.com/hackycy/sf-nest-admin/blob/dev/src/modules/admin/core/guards/auth.guard.ts

**Comment by reactleaner** [comment]
😃好的 感谢大佬细心解答！
