### ISSUE TITLE
serve端报错

### ISSUE THREAD

**Issue by gggso** [hackycy/sf-nest-admin#18]
## Bug report（问题描述）
server端启动后 报 
`Generic type 'RemoteSocket<EmitEvents, SocketData>' requires 2 type argument(s).`
我把这个错误修复后又报 
`ERROR [ApiExceptionFilter] TypeError: classTransformer.plainToClass is not a function`
问下，是有什么依赖没有锁定么。

#### Screenshot or Gif（截图或动态图）

![image](https://user-images.githubusercontent.com/6212790/150949558-dd999afe-c632-45bd-849d-128832bd86e9.png)

#### Other relevant information（格外信息）
- Your mac:
- Node.js v16.13.1:
- nest 8.2.0

**Comment by hackycy** [comment]
@gggso 第二个报错我并没有复现出来，直接编译运行报错的吗还是执行接口异常

**Comment by gggso** [comment]
@hackycy run dev 报错的。是不是我依赖太高了 。。方便说下你本地的版本依赖么。。我锁死了试下

**Comment by gggso** [comment]
@hackycy 更正一下。是请求登录验证码图片引发的报错

**Comment by hackycy** [comment]
@gggso 你锁死一下`class-transformer`和`class-validator`版本

**Comment by gggso** [comment]
@hackycy    是不是
"class-transformer": "0.4.0",
"class-validator": "0.13.1",

**Comment by hackycy** [comment]
@gggso 
是的，删除掉`lock`文件和`node_modules`，重新安装一次。
问题请看这个https://github.com/nestjs/nest/issues/8637。
