### ISSUE TITLE
sf-vue-admin issue 呢？关于table 封装的建议

### ISSUE THREAD

**Issue by Yaob1990** [hackycy/sf-nest-admin#2]
目前实现代码
![image](https://user-images.githubusercontent.com/22534346/121272713-4382f580-c8f9-11eb-9ce1-2f776cadc09d.png)

用户必须传递 promise。这里感觉不是特别优雅。

我的想法是尽量减少用户的感知，不管你怎么给我，只要是符合我要求的数据结构，我都能处理。

![image](https://user-images.githubusercontent.com/22534346/121272886-a2486f00-c8f9-11eb-9004-cdba438c96e4.png)

这样嵌套一层 promise ，给我一般数据，我也能处理。

小小建议哈。

**Comment by hackycy** [comment]
@Yaob1990 
哪边实现都可以的，外面数据如果不是异步处理的，也可以用`Promise.resolve(data)`包一层返回也可以的。但是这里的数据来源基本是异步的，也不用担心不是Promise的情况。还是看项目而言吧，也尽量减少不必要的包装吧。

**Comment by hackycy** [comment]
@Yaob1990 关于前端的issue已经关了，具体在使用某个后端的仓库进行发起issue哈。
