### ISSUE TITLE
跑起来了，任意接口报这个错误

### ISSUE THREAD

**Issue by lyseky** [hackycy/sf-nest-admin#20]
{
    "code": 500,
    "data": null,
    "message": "TypeError: classTransformer.plainToClass is not a function"
}

**Comment by hackycy** [comment]
@lyseky 
<img width="262" alt="image" src="https://user-images.githubusercontent.com/26972260/166853680-4e6fa132-a0a3-42a4-85f0-b5bcad06ed00.png">
看一下你的`package.json`的这两个依赖包版本

**Comment by hackycy** [comment]
@vacrain 
`NestJs`官方支持`express`和`fastify`框架，至于fastify如何可以自己查阅相关的性能测试对比。

https://docs.nestjs.com/techniques/performance#performance-fastify

**Comment by vacrain** [comment]
> @vacrain `NestJs`官方支持`express`和`fastify`框架，至于fastify如何可以自己查阅相关的性能测试对比。
> 
> https://docs.nestjs.com/techniques/performance#performance-fastify

谢谢~ 有讨论群啥的吗

**Comment by vacrain** [comment]
> @vacrain `NestJs`官方支持`express`和`fastify`框架，至于fastify如何可以自己查阅相关的性能测试对比。
> 
> https://docs.nestjs.com/techniques/performance#performance-fastify

好嘞，谢谢！
