### ISSUE TITLE
FastifyWarning.fastify-formbody: fastify-formbody has been deprecated. Use @fastify/formbody@6.0.0 instead.

### ISSUE THREAD

**Issue by teastack** [hackycy/sf-nest-admin#23]
刚启动时没提示，后面启动都报FastifyWarning.fastify-formbody: fastify-formbody has been deprecated. Use @fastify/formbody@6.0.0 instead.

**Comment by Akenokoru** [comment]
> 刚启动时没提示，后面启动都报FastifyWarning.fastify-formbody: fastify-formbody has been deprecated. Use @fastify/formbody@6.0.0 instead.


联系一下作者大大更新下lock文件Orz..

**Comment by hackycy** [comment]
目测排查原因应该是Swagger导致的，`fastify-swagger`只更新到了5.2.0就被弃用了，但`@nest/swagger`官方仍在使用。觉得难受可以尝试移除掉swagger文档查看还有没有报这个警告。

**Comment by teastack** [comment]
> 这个报错导致项目跑不起来，当前node版本14.18.0，屏蔽代码setupSwagger也不行

**Comment by hackycy** [comment]
@teastack 我运行测试没有问题，而且貌似那只是警告。
如果确定项目配置文件配置无误还是无法运行请贴出更多完整的错误提示。

**Comment by teastack** [comment]
奇怪，我重装了下mysql，虽然警告还在，但项目可以跑起来正常开发，目前排查不出来什么原因

**Comment by teastack** [comment]
奇怪，我重装了下mysql，虽然警告还在，但项目可以跑起来正常开发，目前排查不出来什么原因
