### ISSUE TITLE
sfadmin create后server无法加载

### ISSUE THREAD

**Issue by Wanger** [hackycy/sf-nest-admin#24]
debian 11 nodejs 12或者14 用cli全新安装后
npn run dev后提示
[2:31:50 PM] Starting compilation in watch mode...

node_modules/@nestjs/typeorm/dist/common/typeorm.decorators.d.ts:2:10 - error TS2305: Module '"typeorm"' has no exported member 'DataSource'.

2 import { DataSource, DataSourceOptions } from 'typeorm';
           ~~~~~~~~~~

node_modules/@nestjs/typeorm/dist/common/typeorm.decorators.d.ts:2:22 - error TS2305: Module '"typeorm"' has no exported member 'DataSourceOptions'.

2 import { DataSource, DataSourceOptions } from 'typeorm';
                       ~~~~~~~~~~~~~~~~~

node_modules/@nestjs/typeorm/dist/common/typeorm.utils.d.ts:3:10 - error TS2305: Module '"typeorm"' has no exported member 'DataSource'.

3 import { DataSource, DataSourceOptions } from 'typeorm';
           ~~~~~~~~~~

node_modules/@nestjs/typeorm/dist/common/typeorm.utils.d.ts:3:22 - error TS2305: Module '"typeorm"' has no exported member 'DataSourceOptions'.

3 import { DataSource, DataSourceOptions } from 'typeorm';
                       ~~~~~~~~~~~~~~~~~

node_modules/@nestjs/typeorm/dist/interfaces/typeorm-options.interface.d.ts:2:10 - error TS2305: Module '"typeorm"' has no exported member 'DataSource'.

2 import { DataSource, DataSourceOptions } from 'typeorm';
           ~~~~~~~~~~

node_modules/@nestjs/typeorm/dist/interfaces/typeorm-options.interface.d.ts:2:22 - error TS2305: Module '"typeorm"' has no exported member 'DataSourceOptions'.

2 import { DataSource, DataSourceOptions } from 'typeorm';
                       ~~~~~~~~~~~~~~~~~

node_modules/@nestjs/typeorm/dist/typeorm.module.d.ts:2:10 - error TS2305: Module '"typeorm"' has no exported member 'DataSource'.

2 import { DataSource, DataSourceOptions } from 'typeorm';
           ~~~~~~~~~~

node_modules/@nestjs/typeorm/dist/typeorm.module.d.ts:2:22 - error TS2305: Module '"typeorm"' has no exported member 'DataSourceOptions'.

2 import { DataSource, DataSourceOptions } from 'typeorm';
                       ~~~~~~~~~~~~~~~~~

src/modules/admin/system/online/online.service.ts:63:49 - error TS2314: Generic type 'RemoteSocket<EmitEvents, SocketData>' requires 2 type argument(s).

63   async findSocketIdByUid(uid: number): Promise<RemoteSocket<unknown>> {
                                                   ~~~~~~~~~~~~~~~~~~~~~

[2:32:08 PM] Found 9 errors. Watching for file changes.

**Comment by hackycy** [comment]
cli的模版没更新，直接clone项目吧

**Comment by Wanger** [comment]
> cli的模版没更新，直接clone项目吧

感谢，搞掂能运行了，然后请问 前端是直接clone dev分支还是nest分支？

**Comment by hackycy** [comment]
@Wanger 前端用`dev`分支就行。
