### ISSUE TITLE
nest-cli的生成模块功能无效

### ISSUE THREAD

**Issue by 0cafe** [hackycy/sf-nest-admin#25]
项目根目录下命令行输入 nest g mo api 之类的nest-cli命令 ，无反应。

**Comment by hackycy** [comment]
`npx nest g mo api`这些呢？直接用`nest`命令需要全局安装`nest`

**Comment by 0cafe** [comment]
> `npx nest g mo api`这些呢？直接用`nest`命令需要全局安装`nest`

`npx nest g mo api` 这个指令可以生成模块 ，nest我全局安装了，自己建的项目也能用nest g mo xx 生成

**Comment by hackycy** [comment]
可能版本不一致吧
