### ISSUE TITLE
为什么要将菜单项放在后端呢？这样做有什么好处？

### ISSUE THREAD

**Issue by 851248662** [hackycy/sf-nest-admin#9]
小弟是菜鸟全干工程师一枚，我去看了 vue-element-admin 这个项目，发现他的路由是写在前端的。但是此项目的菜单路由是写在后端的。如果这样做的话路由不是需要在后端加，真实页面得在前端加，这样不会有点奇怪吗？  或者有其它考量呢？ 望大佬赐教，小弟不胜感激。

**Comment by hackycy** [comment]
不管路由写在前端还是后端，前端都要负责实现页面，但是这里只是把路由交给了后端进行控制。前端只是负责实现好页面，并映射。前端配合Api接口以及动态路由来实现菜单权限控制。

写不写在前端是需要你对后台页面菜单级别的权限控制的需求来定的。

**Comment by 851248662** [comment]
好的  谢谢解答

**Comment by hackycy** [comment]
如有别的疑问再重新发起issue提问吧
